import sys
from pathlib import Path
sys.path.append(str(Path.resolve(Path(__file__).resolve().parent / '../../RMpy package')))
# have to look 2 levels up for the folder containing the package

import RMpy.RMDate
from datetime import date
import RMpy.common as RMc
import datetime

# This test the functions in RMpy.RMDate

# ===================================================DIV60==
def main():

    date_test_database_folder = Path(r"C:\Users\rotter\dev\Genealogy\Test Data\RMDate and SortDate test data")
    date_test_database_filename = Path(r"TEST DATA Dates -format_v11 -dump -reduced -v003 -RW.rmtree")

    # Use UTF-8 encoding for the report file. Test for write-ability
    report_path = Path("RMpy Package", "testing", "Result_Reports", r"Test_Results  " + RMc.time_stamp_now("file") + ".txt")
    report_file = open(report_path,  mode='w', encoding='utf-8')

    db_path = date_test_database_folder / date_test_database_filename

    # RM database file info
    file_modification_time = datetime.datetime.fromtimestamp(
        db_path.stat().st_mtime)

     # write header to report file
    format = "%Y-%m-%d %H:%M:%S"
    report_file.write(
            F"Report generated at      = {RMc.time_stamp_now()}\n"
            F"Utility name             = RMDate -test\n"
            F"Python version           = v{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}\n"
            F"Database last changed on = {file_modification_time.strftime(format)}\n"
            F"Database processed       = {db_path.resolve()}\n"
            F"\n\n\n")

    test_data = get_test_data(db_path)
    test_data = test_case_order(test_data)

    display_test_data(test_data, report_file)
    
    report_file.write("\nToday, RMdate, RMSortDate")
    report_file.write(str(date.today()) + '\n')
    report_file.write(RMpy.RMDate.now_RMDate() + '\n' )
    report_file.write(str(RMpy.RMDate.now_RMSortDate()) + '\n')
   
    report_file.write("===========================================DIV50==\n")

    try:
        RunTestList = False

        for item in test_data:
            if RunTestList:
                # run just these tests
                if item[0] not in ( 77,):   
                    continue
            else:
                pass
                # SKIP THESE TESTS
    
              #  if item[0] in (38, 39, 40): 
              #      continue # SORT date set differently than main date
              #  if item[0] in (66,): 
              #      continue # out of range date, sort date generated by RM is wrong

            # skip these
            if item[1] in ('C_Quaker', 'C_JulGeor', 'Quar_1', 'Quar_2'):
                continue

            Test(item, report_file)
        pass
   # PauseWithMessage()
    except RMc.RM_Py_Exception as exp:
        report_file.write(str(exp))
    
    finally:
        report_file.close()

    return


# ===================================================DIV60==
def Test(test_item, report_file):
    try:
        test_english_date_from_DB_SortDate = True
        test_RMDate_from_DBSortDate = True
        test_english_date_from_DB_RMDate = False
        test_SortDate_from_RMDate = True

        #   types of date
        #   human readable with 8 formats and internal storage date
        #   internal dates can be displayed as human readable in 8 formats
        #   human readable canonical form can be converted to internal storage dates
        #   human readable non-canonical form can be parsed to a canonical form and then converted

        #   internal Date   (RMDate)
        #   internal Sort Date 
        #   human readable Date
        #   human readable Sort Date

        report_file.write(f"\n\n{test_item}\n")
        # print(f"{test_item}\n")

        # parse the test item
        in_DB_EvemtID = test_item[0]
        in_DB_RMdate = test_item[2]
        in_DB_Sortdate = int(test_item[3])
        in_GUI_full_date =  parse_description(test_item[4], 0 )
        in_GUI_sort_date =  parse_description(test_item[4], 1 )
        in_GUI_description = parse_description(test_item[4], 2 )

        # make the function calls and save the results.

        # Test the results against expected
        # test report shows "known correct" = or != "generated"

        if test_RMDate_from_DBSortDate:
            try:
                report_file.write("Compare RMDate in DB  vs. RMDate derived from DB SortDate\n")
                out_RMDate_from_SortDate= RMpy.RMDate.RMSortDate_int_TO_RMDate_str(in_DB_Sortdate)
                if in_DB_RMdate != out_RMDate_from_SortDate:
                    report_file.write(F"{in_DB_EvemtID}  ======= '{in_DB_RMdate}'  !=  '{out_RMDate_from_SortDate}'\n")
                else:
                    report_file.write(F"{in_DB_EvemtID}          '{in_DB_RMdate}'  ==  '{out_RMDate_from_SortDate}'\n")
            except Exception as e:                        
                report_file.write("\n========================== A test case caused an exception. Continue with test." + str(e) + "\n")

        if test_english_date_from_DB_SortDate:
            try:
                report_file.write("English date from GUI  vs. English date derived from DB RMDate\n")
                out_english_date_from_DB_SortDate= RMpy.RMDate.RMDate_str_TO_en_str(out_RMDate_from_SortDate, RMpy.RMDate.Format.LONG)
                if in_GUI_full_date != out_english_date_from_DB_SortDate:
                    report_file.write(F"{in_DB_EvemtID} ======== '{in_GUI_full_date}'  !=  '{out_english_date_from_DB_SortDate}'\n")
                else:
                    report_file.write(F"{in_DB_EvemtID}          '{in_GUI_full_date}'  ==  '{out_english_date_from_DB_SortDate}'\n")
            except Exception as e:                        
                report_file.write("\n========================== A test case caused an exception. Continue with test." + str(e) + "\n")

        # DB internal date to human readable vs GUI date
        if test_english_date_from_DB_RMDate:
            try:
                report_file.write("English format as shown in RM GUI  vs. English format derived from RMDate in DB\n")
                out_engliah_date_from_DB_RMDate= RMpy.RMDate.RMDate_str_TO_en_str(in_DB_RMdate, RMpy.RMDate.Format.LONG)
                if out_engliah_date_from_DB_RMDate != in_GUI_full_date:
                    report_file.write(F"{in_DB_EvemtID} ======= '{in_GUI_full_date}'  !=  '{out_engliah_date_from_DB_RMDate}'\n")
                else:
                    report_file.write(F"{in_DB_EvemtID}         '{in_GUI_full_date}'  ==  '{out_engliah_date_from_DB_RMDate}'\n")
            except Exception as e:                        
                report_file.write("\n========================== A test case caused an exception. Continue with test." + str(e) + "\n")

        if test_SortDate_from_RMDate:
            try:
                report_file.write("Sort date from DB  vs.  sort date derived from DB RMDate\n")
                out_SortDate_from_DB_RMDate = RMpy.RMDate.RMDate_str_TO_RMSortDate_int(in_DB_RMdate)
                if out_SortDate_from_DB_RMDate != in_DB_Sortdate:
                    report_file.write(F"{in_DB_EvemtID} ======= '{in_DB_Sortdate}'  !=  '{out_SortDate_from_DB_RMDate}'\n")
                else:
                    report_file.write(F"{in_DB_EvemtID}         '{in_DB_Sortdate}'  ==  '{out_SortDate_from_DB_RMDate}'\n")
            except Exception as e:                        
                report_file.write("\n========================== A test case caused an exception. Continue with test." + str(e) + "\n")

        if test_english_date_from_DB_SortDate:
            try:
                report_file.write("English sort date from RM GUI  vs.  English format from sort date\n")
                out_english_date_from_DB_SortDate
                if in_GUI_sort_date != out_english_date_from_DB_SortDate:
                    report_file.write(F"{in_DB_EvemtID} ======= '{in_GUI_sort_date}'  !=  '{out_english_date_from_DB_SortDate}'\n")
                else:
                    report_file.write(F"{in_DB_EvemtID}         '{in_GUI_sort_date}'  ==  '{out_english_date_from_DB_SortDate}'\n")
            except Exception as e:                        
                report_file.write("\n========================== A test case caused an exception. Continue with test." + str(e) + "\n")

        

    except Exception as e:
        report_file.write("\n========================== A test case caused an exception. Continue with test." + str(e) + "\n")

# ===================================================DIV60==
def get_test_data(db_path : Path, display_data : bool = True) -> []:
        
    if not db_path.exists():
        raise RMc.RM_Py_Exception(
            F'ERROR: Database path not found:\n'
            F' "{db_path}"\n')
    
    db_connection = RMc.create_db_connection(db_path, None)

    db_cursor = db_connection.cursor()

    SQL_stmt = """
SELECT EventID, ftt.Name, et.Date, et.SortDate, et.Details
FROM EventTable AS et
INNER JOIN FactTypeTable AS ftt ON et.EventType = ftt.FactTypeID
ORDER BY Name COLLATE NOCASE ASC;  
"""
    db_cursor.execute(SQL_stmt)

    test_data = []
    for row in db_cursor:
        test_data.append( [row[0], row[1], row[2], row[3], row[4], False ] )
    
    return test_data

# ===================================================DIV60==
def test_case_order(test_data : list[T]) -> list[T]:

    tc_order = [
# Std_1
18, 34, 72, 41, 42, 84, 28,
71, 27, 29, 26, 92, 30,
66, 67,
# Std_1 BC
49, 50, 51,
# Std_1_LY
74, 82, 83,
# Std_1 FAIL
38, 39, 40,
# Std_1_Conf
9, 13, 93, 10, 94, 95, 96, 97, 98, 99, 100, 101,
86, 102, 103, 104, 105,
# Std_1 Mod
8, 11, 6, 7, 4, 5, 3, 111,
# Std_1_Mod_p
44, 59, 60, 87, 88, 89, 106,
# Std_1_Mod+Conf
64,
# Std_2_Mod
17, 14, 16, 15,
# Std_2_Mod_RevTL
110, 112, 113, 114,
# Std_2_Mod_p
78, 69,
# Std_2_Dash
35, 36, 37, 91, 75,
58, 55, 107, 108, 109,
56, 53, 32, 54, 57,
# Std_2_Mod+Conf
76, 77, 90,
# Quar_1
46, 47, 48, 79, 80, 81, 45,
# Quar_2
12, 63,
# C_Quaker
20, 21, 22, 23, 25, 31, 33, 73,
# C_JulGeor
19, 43, 52, 62, 68
    ]

    # check for duplicates in tc_order
    seen = set()
    repeated = []
    for x in tc_order:
        if x in seen:
            repeated.append(x)
        else:
            seen.add(x)
    
    test_data_tc_order = []
    # print out the test data in the test cases order
    for tc in tc_order:
        for td in test_data:
            if tc == td[0]:
                test_data_tc_order.append(td)
                td[5] = True
                continue
    
    found_unassigned = []
    for td in test_data:
        if not td[5]:
            found_unassigned.append(td[0])

    if len(repeated) >0 or len(found_unassigned) >0:
        print(f"\n\nThe test case ordering list has a problem:\n")
        if len(found_unassigned) >0:
            print(f"These tests in test data do not appear in test_case ordering: {found_unassigned}\n")
        if len(repeated) >0:
            print(f"There is at least one duplication in test case ordering list: {repeated}.\n")
                

    return test_data_tc_order

# ===================================================DIV60==
def display_test_data(test_data, report_file):

    # Compute max width of each column
    col_widths = [max(len(str(row[i])) for row in test_data)
                for i in range(len(test_data[0]))]

    for row in test_data:
        line = "  ".join(str(val).ljust(col_widths[i])
                        for i, val in enumerate(row)
                    )
        report_file.write( line + '\n')


# ===================================================DIV60==
def parse_description(In, which):
    # Fact description=   full Date || Sort Date  || comments
    # 0 human readable date, format= 10 January 1959
    # 1 human readable sort date, format= 10 January 1959

    # all formats (from RM v9 preferences)
    #  10 Jan 1959
    #  Jan 10, 1959
    #  10 January 1950
    #  January 10, 1959
    #  10 JAN 1959
    #  JAN 10, 1950
    #  10 JANUARY 1950
    #  JANUARY 10, 1950

    parsed=  (In.split("||") [which])
    return parsed.strip()


# ===================================================DIV60==
def PauseWithMessage(message=None):
    if (message != None):
        print(message)
    input("\nPress the <Enter> key to continue...")
    return


# ===================================================DIV60==
# Call the "main" function
if __name__ == '__main__':

    main()

# ===================================================DIV60==
